# Winter School on Tensor Network Methods for Quantum Many-Body Systems: Basic Tensor Operations

In [1]:
from ncon import ncon
import numpy as np
import scipy.linalg as scl

# Creating Tensors

In [22]:
# R, a rank-n tensor (matrix) with dimension 3x3
# Ranke: Number of dimension of tensor
# Shape: number of elements in each dimension

R=np.random.rand(2,4,3)
# R is a MPS (matrix product state)
print(R)
print("Rank:",R.ndim)
print("Shape:",R.shape)
print("N_Elements:",R.size)
print("Accesing Elements",R[1,0,1])

[[[0.45270542 0.69019965 0.87589413]
  [0.77392149 0.65383676 0.39688357]
  [0.98837235 0.06855717 0.13562082]
  [0.98250068 0.33230087 0.14575124]]

 [[0.65598804 0.18534619 0.99046107]
  [0.56149809 0.170675   0.32943442]
  [0.29032191 0.67113249 0.36853741]
  [0.70839032 0.95075669 0.72354046]]]
Rank: 3
Shape: (2, 4, 3)
N_Elements: 24
0.1853461879824302


In [31]:
# R, a rank-2 tensor (matrix) with dimension 3x3
# complex: a+ib
R=np.random.rand(3,3)+1j*np.random.rand(3,3)

# Q, a rank-2 tensor (matrix) with dimension 3x5
Q=np.random.rand(3,5)

# A, a rank-4 tensor (multi-dimensional array) with dimension [2,4,3,6]
A=np.random.rand(2,4,3,6)

# B, a rank-3 tensor (multi-dimensional array) with dimension [2,3,4] filled with 1
B=np.ones([2,3,4])

# C, a rank-3 tensor (multi-dimensional array) with dimension [3,1,4] filled with 0
C=np.zeros([3,1,4])

In [33]:
print(R)
print(1j) #(0+1j)

[[0.4965545 +0.13220413j 0.89010868+0.28548252j 0.39896209+0.4434964j ]
 [0.8707029 +0.93501795j 0.51423904+0.40166742j 0.00212441+0.27999339j]
 [0.45620249+0.33582514j 0.6754446 +0.88421663j 0.18765337+0.62867815j]]
1j


In [21]:
print("Shape Q:",np.shape(Q))
print("Shape A:",np.shape(A))

Shape Q: (3, 5)
Shape A: (2, 4, 3, 6)


In [22]:
print(B)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [23]:
print(C)

[[[0. 0. 0. 0.]]

 [[0. 0. 0. 0.]]

 [[0. 0. 0. 0.]]]


# Contracting Tensors

#### We use **<span style="color:red">ncon</span>** function to contract multiple tensors together

**<span style="color:blue">ncon(L, v, order=None, forder=None, check_indices=True)</span>**
   
   > L = [A1, A2, ..., Ap] list of tensors.

   > v = [v1, v2, ..., vp] list of lists of indices e.g. v1 = [3, 4, -1] labels the three indices of tensor A1, with -1 indicating an uncontracted index (open leg) and 3 and 4 being the contracted indices.

   > order, if present, contains a list of all positive indices - if not
    [1, 2, 3, 4, ...] by default. This is the order in which they are
    contracted.

   > forder, if present, contains the final ordering of the uncontracted indices
    - if not, [-1, -2, ..i] by default.

### Matrix . Matrix
<img src="images/mxm.png" width="200"> 

In [3]:
# T1, a rank-2 tensor (matrix) with dimension 4x3
T1=np.random.rand(4,3)
print("Shape T1:",np.shape(T1))

# T1, a rank-2 tensor (matrix) with dimension 3x5
T2=np.random.rand(3,5)
print("Shape T2:",np.shape(T2))

Tn = T1@T2
# Tn = np.dot(T1,T2)
# Tn = np.matmul(T1,T2)

Tn=ncon([T1,T2], [[-1,1],[1,-2]], [1],[-1,-2])
print("Shape Tn:",np.shape(Tn))

Shape T1: (4, 3)
Shape T2: (3, 5)
Shape Tn: (4, 5)


### Vector . Matrix
<img src="images/vxm.png" width="170"> 

In [41]:
# V1, a rank-1 tensor (vector) with dimension 4
V1=np.random.rand(4,)
print("Shape V1:",np.shape(V1))

# M, a rank-2 tensor (matrix) with dimension 4x5
M=np.random.rand(4,5)
print("Shape T2:",np.shape(M))

V2=ncon([V1,M], [[1],[1,-1]], [1])
print("Shape V2:",np.shape(V2))
print(V2)

Shape V1: (4,)
Shape T2: (4, 5)
Shape V2: (5,)
[0.82023106 0.62447171 1.46771422 0.83664479 1.33122857]


### Vector . Matrix . Vector
<img src="images/vxmxv.png" width="200"> 

In [26]:
# V1, a rank-1 tensor (vector) with dimension 3
V1=np.random.rand(3,)
print("Shape V1:",np.shape(V1))

# M, a rank-2 tensor (matrix) with dimension 3x6
M=np.random.rand(3,6)
print("Shape M:",np.shape(M))

# V2, a rank-1 tensor (vector) with dimension 6
V2=np.random.rand(6,)
print("Shape V2:",np.shape(V2))

C1=ncon([V1,M,V2], [[1],[1,2],[2]], [1,2])

C2=V1 @ M @ V2

C3=np.dot(V1,np.dot(M,V2))

print("Shape C1:", np.shape(C1), ", C1=",C1 , ", C2=",C2 , ", C3=",C3)

Shape V1: (3,)
Shape M: (3, 6)
Shape V2: (6,)
Shape C1: () , C1= 3.1930697351220214 , C2= 3.1930697351220214 , C3= 3.193069735122022


### Trace
<img src="images/trace.png" width="300"> 

In [27]:
# M1, a rank-2 tensor (matrix) with dimension 3x6
M1=np.random.rand(3,6)
print("Shape M1:",np.shape(M1))

# M2, a rank-2 tensor (matrix) with dimension 6x4
M2=np.random.rand(6,4)
print("Shape M2:",np.shape(M2))

# M3, a rank-2 tensor (matrix) with dimension 4x8
M3=np.random.rand(4,8)
print("Shape M3:",np.shape(M3))

# M4, a rank-2 tensor (matrix) with dimension 8x3
M4=np.random.rand(8,3)
print("Shape M4:",np.shape(M4))

Trace=ncon([M1,M2,M3,M4], [[1,2],[2,3],[3,4],[4,1]], [1,2,3,4])
print("Trace[M1,M2,M3,M4]=",Trace)

Shape M1: (3, 6)
Shape M2: (6, 4)
Shape M3: (4, 8)
Shape M4: (8, 3)
Trace[M1,M2,M3,M4]= 43.037180771097965


### Contraction of rank-n Tensors
<img src="images/cont4x3.png" width="600"> 

In [42]:
# A, a rank-4 tensor with dimension [4,3,5,8]
A=np.random.rand(4,3,5,8)
print("Shape A:",np.shape(A))

# B, a rank-3 tensor with dimension [3,5,2]
B=np.random.rand(3,5,2)
print("Shape B:",np.shape(B))

C=ncon([A,B], [[-1,1,2,-2],[1,2,-3]], [1,2],[-2,-3,-1])
print("Shape C:",np.shape(C))

Shape A: (4, 3, 5, 8)
Shape B: (3, 5, 2)
Shape C: (8, 2, 4)


# Reshaping Tensors

### Join Tensor Legs
<img src="images/joinleg.png" width="600"> 

In [4]:
# T, a rank-3 tensor with dimension [3,5,2]
T=np.random.rand(3,5,2)
print("Shape T:",np.shape(T))

Tj=np.reshape(T,[3,10])
print("Shape of reshaped tensor Tj:",np.shape(Tj))
Tk=np.reshape(Tj,[3,5,2])
print("Shape of reshaped tensor Tk:",np.shape(Tk))

Shape T: (3, 5, 2)
Shape of reshaped tensor Tj: (3, 10)
Shape of reshaped tensor Tk: (3, 5, 2)


### Join Tensor Legs
<img src="images/splitleg.png" width="600"> 

In [47]:
# T, a rank-2 tensor with dimension [5,6]
T=np.random.rand(2,3)
print("Shape T:",np.shape(T))

Ts=np.reshape(T,[6])
print("Shape of reshaped tensor Ts:",np.shape(Ts),"\n")

print(T,"\n")
print(Ts)


Shape T: (2, 3)
Shape of reshaped tensor Ts: (6,) 

[[0.66556153 0.59287863 0.00106229]
 [0.64935074 0.61832677 0.20776169]] 

[0.66556153 0.59287863 0.00106229 0.64935074 0.61832677 0.20776169]


### Transpose (permute) Tensor Legs
<img src="images/permuteleg.png" width="600"> 

In [48]:
# T, a rank-3 tensor with dimension [3,5,2]
T=np.random.rand(3,5,2)
print("Shape T:",np.shape(T))

Tp=np.transpose(T,[0,2,1])
print("Shape of transposed tensor Tp:",np.shape(Tp))

Shape T: (3, 5, 2)
Shape of transposed tensor Tp: (3, 2, 5)


# Tensor Decomposition

### Singular-Value Decomposition
<img src="images/svd.png" width="800"> 

In [32]:
# Virtual Bond Dimension D
D=5

# Physical Bond Dimension p
p=2

# Truncation Dimension chi (sometimes chi is called boundary dimension)
chi=3

# A, a rank-3 MPS with dimension [D,D,p]
A=np.random.rand(D,D,p)

# B, a rank-3 MPS with dimension [D,D,p]
B=np.random.rand(D,D,p)

print("Shape A:",np.shape(A), ",  Shape B:",np.shape(B),"\n")

# Contract A,B to Build theta
theta=ncon([A,B], [[-1,1,-2],[1,-3,-4]], [1])
print("Shape theta:",np.shape(theta))

theta=np.reshape(theta, [D*p,D*p])
print("Shape theta after reshape:",np.shape(theta))

# SVD theta:  theta=U.S.Vd   ---> Note that np.svd returns V^\dagger automatically
U,S,Vd=np.linalg.svd(theta)
print("Shape U:",np.shape(U), ",  Shape S:",np.shape(S), ",  Shape Vd:",np.shape(Vd))

# theta2=U.S.Vd   ---> Note that np.svd returns V^\dagger automatically
theta2=U@np.diag(S)@Vd
print("theta==theta2:", np.allclose(theta,theta2))

# Truncate the shared dimension of U,S,Vd back to D
U=U[ : , 0:chi ]

S=S[ 0:chi ]

Vd=Vd[ 0:chi , : ]

print()
print("Shape U:",np.shape(U), ",  Shape S:",np.shape(S), ",  Shape V:",np.shape(Vd))

# Reshape back the tensor to original shape
A=U@np.diag(np.sqrt(S))
A=np.reshape(A, [D,p,chi])
A=np.transpose(A,[0,2,1])

B=np.diag(np.sqrt(S))@Vd
B=np.reshape(B, [chi,D,p])

print()
print("Shape A:",np.shape(A), ",  Shape B:",np.shape(B))

Shape A: (5, 5, 2) ,  Shape B: (5, 5, 2) 

Shape theta: (5, 2, 5, 2)
Shape theta after reshape: (10, 10)
Shape U: (10, 10) ,  Shape S: (10,) ,  Shape Vd: (10, 10)
theta==theta2: True

Shape U: (10, 3) ,  Shape S: (3,) ,  Shape V: (3, 10)

Shape A: (5, 3, 2) ,  Shape B: (3, 5, 2)


### Eigenvalue Decomposition

In [33]:
# Virtual Bond Dimension D
D=6

# M, a rank-2 matrix with dimension [D,D] --> M is Hermitian
M=np.random.rand(D,D)

# Full Diagonalization of a square matrix
E,W=np.linalg.eig(M)

print("1d array of eigenvalues: ",E,"\n")

# Make M Hermitian
M=(M+M.conj().T)/2.0

# Full Diagonalization of a symmetric Hermitianmatrix
E,W=np.linalg.eigh(M)

print("1d array of eigenvalues: ",E)

1d array of eigenvalues:  [ 3.8281759 +0.j         -1.02770789+0.j          0.41839579+0.j
 -0.03352116+0.40243406j -0.03352116-0.40243406j -0.12468863+0.j        ] 

1d array of eigenvalues:  [-1.03868581 -0.27435953 -0.10840892  0.17649549  0.41321058  3.85888104]


$$M=W.E.W^\dagger$$