In [1]:
using LinearAlgebra

In [2]:
function H0(L)
    ⊗(x,y)=kron(x,y)
    sp = [0 1;0 0];
    sm = [0 0;1 0];
    id = [1 0;0 1];
    z = [1 0;0 -1];
    H1 = fill(id,L)
    H1[1] = sp
    H1[2] = sm
    H2 = fill(id,L)
    H2[1] = sm
    H2[2] = sp 
    H0 = zeros(Int,2^L,2^L)
    for j in 1:L-1
        H0 += -1im*(foldl(⊗,H1))+1im*(foldl(⊗,H2))
        H1 = circshift(H1,1)
        H2 = circshift(H2,1)
    end
    return H0
end

function Hm(L,m)
    ⊗(x,y)=kron(x,y)
    sp = [0 1;0 0];
    sm = [0 0;1 0];
    spm = [1 0;0 0];
    smp = [0 0;0 1];
    id = [1 0;0 1];
    z = [1 0;0 -1];
    H1 = fill(id,L)
    H1[1] = spm
    Hm = zeros(Int,2^L,2^L)
    for j in 1:L
        Hm += (((-1)^j)*m)*(foldl(⊗,H1))
        H1 = circshift(H1,1)
    end
    return Hm
end

function Hg(L,G²)
    ⊗(x,y)=kron(x,y)
    sp = [0 1;0 0];
    sm = [0 0;1 0];
    spm = [1 0;0 0];
    smp = [0 0;0 1];
    id = [1 0;0 1];
    z = [1 0;0 -1]; 
    H1 = fill(id,L)
    H1[1] = spm
    Hg = zeros(Int,2^L,2^L)
    for j in 1:L-1
        Hg += (G²/2.0)*(foldl(⊗,H1))
        H1 = circshift(H1,1)
    end
    return Hg
end

function H_GN(L,m,G²)
    H_GN = H0(L) + Hm(L,m) + Hg(L,G)
    return H_GN
end

H_GN (generic function with 1 method)

In [10]:
# H_GN(L,m,G)
eigvals(H_GN(4,1,1))

16-element Vector{Float64}:
 -2.1481316019009062
 -1.44160103982396
 -0.833069197027375
 -0.706530562076945
 -0.1265386349504306
  0.0
  0.1849375951264702
  0.6085318427965858
  0.8914681572034164
  1.31506240487353
  1.5
  1.6265386349504292
  2.2065305620769453
  2.333069197027375
  2.941601039823961
  3.648131601900905

In [16]:
v1 = eigvecs(H_GN(4,1,1))[:,1]
# v2 = eigvecs(H_GN(5,1,1))[:,1];
# println(length(v1), "\n", length(v2))

16-element Vector{ComplexF64}:
                     0.0 + 0.0im
 -5.4008530518638226e-20 - 1.3074732109947234e-18im
 -3.4623611286739857e-18 + 1.4302169643863553e-19im
   4.336808689942018e-18 - 0.2600945622883989im
   5.392642882359456e-19 + 1.3054856404051141e-17im
       -0.81881191102269 + 4.046596569785026e-18im
    4.85722573273506e-17 + 0.36933427508865396im
                     0.0 + 0.0im
                     0.0 - 1.734723475976807e-18im
                     0.0 + 0.3106749936809706im
     0.15923385450473646 + 0.0im
                     0.0 + 0.0im
   -4.85722573273506e-17 - 0.06013064244633187im
                     0.0 + 0.0im
                     0.0 + 0.0im
                     0.0 + 0.0im

In [20]:
round.(v1; sigdigits=2)
#  trunc(x; digits::Integer= [, base = 10])

16-element Vector{ComplexF64}:
      0.0 + 0.0im
 -5.4e-20 - 1.3e-18im
 -3.5e-18 + 1.4e-19im
  4.3e-18 - 0.26im
  5.4e-19 + 1.3e-17im
    -0.82 + 4.0e-18im
  4.9e-17 + 0.37im
      0.0 + 0.0im
      0.0 - 1.7e-18im
      0.0 + 0.31im
     0.16 + 0.0im
      0.0 + 0.0im
 -4.9e-17 - 0.06im
      0.0 + 0.0im
      0.0 + 0.0im
      0.0 + 0.0im

In [22]:
ARGS

1-element Vector{String}:
 "/home/amin/.local/share/jupyter" ⋯ 26 bytes ⋯ "eaa-4067-b9b7-1f492d0c818e.json"

In [ ]:
parse(In)