## Import libraries 

In [1]:
# if it's not is installed it can be installed as follows 
# ! pip install numpy 

In [5]:
# import numpy in working file 
import numpy as np 

My plan is as follows :
- [x] Array creation 
- [x] Arrange method 
- [x] Ones and zeros
- [x] One-dimensional array 
- [x] Split an array
- [x] Two-dimensional array
- [x] Random array 
- [x] Create a vector 
- [x] Create a matrix 
- [x] Vector-Vector multiplication
- [x] Matrix-Vector multiplication
- [x] Matrix-Matrix multiplication


## Arrary Creation 

In [6]:
arr1 = np.array([1,2,3,4])
print(arr1)

[1 2 3 4]


## Arange Methods 

In [7]:
arr2 = np.arange(0,1,0.1)
print(arr2)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


## Ones and Zeros Array

In [11]:
arr3 = np.ones(5)
print(arr3)

[1. 1. 1. 1. 1.]


In [12]:
arr4 = np.zeros(5)
print(arr4)

[0. 0. 0. 0. 0.]


## One dimensional array 

In [13]:
arr5 = np.arange(16)
print(arr5)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


## Split an array 

In [15]:
print(len(arr5))

16


In [18]:
print(np.ndim(arr5))

1


In [16]:
print(np.shape(arr5))

(16,)


In [19]:
arr5_1 = arr5[0:5]
print(arr5_1)

[0 1 2 3 4]


In [21]:
arr5_2 = arr5[10:]
print(arr5_2)

[10 11 12 13 14 15]


## Two Dimensional Array

In [59]:
arr6 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr6)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [60]:
print(np.arange(16).reshape(4,4))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


## Random Array

In [61]:
arr7 = np.random.rand(3,3)
print(arr7)

[[0.80086378 0.68689534 0.19669016]
 [0.92629127 0.61584474 0.59107523]
 [0.23921117 0.83039132 0.94525639]]


## Creat a Vector 

In [62]:
v1 = np.array([1,2,3,4,5])
print(v1)

[1 2 3 4 5]


In [63]:
v2 = np.array([6,7,8,9,10])
print(v2)

[ 6  7  8  9 10]


## Vector Multiplication

In [66]:
vm1 = np.dot(v1,v2)
print(vm1)

130


## Matrix Creation 

In [67]:
m1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(m1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [68]:
m2 = np.array([[9,8,7],[6,5,4],[3,2,1]])
print(m2)

[[9 8 7]
 [6 5 4]
 [3 2 1]]


## Matrix Multiplication 

In [69]:
np.dot(m1,m2)

array([[ 30,  24,  18],
       [ 84,  69,  54],
       [138, 114,  90]])

## Matrix-Vector Multiplication

In [73]:
m3 = np.arange(12).reshape(4,3)
print(m3)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [74]:
v3 = np.array([1,2,3])
print(v3)

[1 2 3]


In [75]:
np.dot(m3,v3)

array([ 8, 26, 44, 62])