In [1]:
import numpy as np 
from qiskit import QuantumCircuit
from qiskit.quantum_info import DensityMatrix, partial_trace, Statevector, entropy


In [75]:

X = []
D = []
for i in np.arange(0,1.1,0.5):
    for j in np.arange(0,1.1,0.5):
        for k in np.arange(0,1.1,0.5):
            for l in np.arange(0,1.1,0.5):
                if DensityMatrix([[i,j],[k,l]]).is_valid() and DensityMatrix([[i,j],[k,l]]).trace() == 1:
                    X.append([i,j,k,l])
                    D.append(DensityMatrix([[i,j],[k,l]]))
                    
                    

In [43]:
A = np.zeros()
for a in range(8):
    for i in np.linspace(0,1,3):
        for j in np.linspace(0,1,3):
            for k in np.linspace(0,1,3):
                for l in np.linspace(0,1,3):
                    A[a,0]
                
                

In [126]:
A = np.zeros((4,1))
D = []
d = 0.5
for a0 in np.arange(0,1.1,d):
    A[0,0] = a0
    for a1 in np.arange(0,1.1,d):
        A[1,0] = a1
        for a2 in np.arange(0,1.1,d):
            A[2,0] = a2
            for a3 in np.arange(0,1.1,d):
                A[3,0] = a3
                B = DensityMatrix(np.outer(A,A))
#                 B = B/B.trace()
                B2 = DensityMatrix(np.matmul(B.data,B.data))
                if B.is_valid() and B2.is_valid():
                    D.append(B)
                    


In [132]:
len(D)
D[1]

DensityMatrix([[0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
               [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
               [0.+0.j, 0.+0.j, 1.+0.j, 0.+0.j],
               [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j]],
              dims=(2, 2))


In [125]:
test = DensityMatrix(D[37])
test2 = DensityMatrix(np.matmul(test.data,test.data))
test2.is_valid()

True

In [136]:
A = np.zeros((8,1))
D = []
start = 0;
stop = 1.1;
step = 0.5;

for a0 in np.arange(start, stop, step):
    A[0,0] = a0
    for a1 in np.arange(start, stop, step):
        A[1,0] = a1
        for a2 in np.arange(start, stop, step):
            A[2,0] = a2
            for a3 in np.arange(start, stop, step):
                A[3,0] = a3
                for a4 in np.arange(start, stop, step):
                    A[4,0] = a4
                    for a5 in np.arange(start, stop, step):
                        A[5,0] = a5
                        for a6 in np.arange(start, stop, step):
                            A[6,0] = a6
                            for a7 in np.arange(start, stop, step):
                                A[7,0] = a7
                                ρ = DensityMatrix(np.outer(A,A))
#                                 ρ = ρ/ρ.trace()
                                ρ_2 = DensityMatrix(np.matmul(ρ.data,ρ.data))
                                if ρ.is_valid() and ρ_2.is_valid():
                                    D.append(ρ)
                                    
                                

In [137]:
len(D)

78

In [83]:
ar = DensityMatrix(np.outer(A,A))
ar2 = np.matmul(ar,ar)

ar = ar/np.trace(ar)
ar2 = ar2/np.trace(ar2)
print(ar.is_valid())
# print(ar2.is_valid())
print(ar.purity())


True
(1+0j)


In [84]:
ar.to_dict()

{'1|1': (0.5+0j), '2|1': (0.5+0j), '1|2': (0.5+0j), '2|2': (0.5+0j)}

In [93]:
np.real(ar)

array([[0. , 0. , 0. ],
       [0. , 0.5, 0.5],
       [0. , 0.5, 0.5]])

In [99]:
np.real(ar.expand(ar).to_dict())

array({'11|11': (0.25+0j), '12|11': (0.25+0j), '21|11': (0.25+0j), '22|11': (0.25+0j), '11|12': (0.25+0j), '12|12': (0.25+0j), '21|12': (0.25+0j), '22|12': (0.25+0j), '11|21': (0.25+0j), '12|21': (0.25+0j), '21|21': (0.25+0j), '22|21': (0.25+0j), '11|22': (0.25+0j), '12|22': (0.25+0j), '21|22': (0.25+0j), '22|22': (0.25+0j)},
      dtype=object)

In [95]:
ar.probabilities()

array([0. , 0.5, 0.5])

In [96]:
ar.to_dict()

{'1|1': (0.5+0j), '2|1': (0.5+0j), '1|2': (0.5+0j), '2|2': (0.5+0j)}

In [105]:
aa = ar.data@ar.data
aad = DensityMatrix()

In [108]:
aad.is_valid()

True

In [109]:
np.matmul(ar.data,ar.data)

array([[0. +0.j, 0. +0.j, 0. +0.j],
       [0. +0.j, 0.5+0.j, 0.5+0.j],
       [0. +0.j, 0.5+0.j, 0.5+0.j]])

In [1]:
import numpy as np 

In [2]:
a = np.array([1,2,3])
b = np.array([10,20,30])


In [3]:
np.dot(a,b)

140

In [10]:
np.outer(a,a)

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

In [25]:
np.tensordot(a,b,axes=0)

array([[10, 20, 30],
       [20, 40, 60],
       [30, 60, 90]])

In [29]:
np.matmul(np.outer(a,b),np.outer(a,b))

array([[ 1400,  2800,  4200],
       [ 2800,  5600,  8400],
       [ 4200,  8400, 12600]])

In [22]:
np.kron(a,b)

array([10, 20, 30, 20, 40, 60, 30, 60, 90])

In [ ]:
np.dot()
np.outer()
np.tensordot()
np.kron()
np.matmul()