# Qiskit_nature

$$
h^{p}_{q} = h^{q}_{p}
$$
$$
h_{rs}^{pq} = h_{sr}^{qp}
$$
$$
h^{pq}_{rs} = h^{sq}_{rp} = h^{pr}_{qs} = h^{sr}_{qp}
$$

In [1]:
import numpy as np 
from qiskit_nature.units import DistanceUnit 
from qiskit_nature.second_q.drivers import PySCFDriver

In [17]:
driver = PySCFDriver(
atom = "H 0 0 0",
# atom="H 0 0 0; H 0 0 0.74",
# atom="H 0 0 0; H 0 0 0.74; H 0 0 1.48",
basis="sto3g",
charge=0,
# spin = 0,
spin=1,
unit=DistanceUnit.ANGSTROM)
problem = driver.run()

In [18]:
hamiltonian = problem.hamiltonian
coefficients = hamiltonian.electronic_integrals
fermionic_op = hamiltonian.second_q_op()

In [5]:
print(coefficients.alpha)

Polynomial Tensor
 "+-":
[[-1.25330979e+00 -2.22044605e-16]
 [-1.11022302e-16 -4.75068849e-01]]
 "++--":
[[[[6.74755927e-01 1.17961196e-16]
   [3.33066907e-16 1.81210462e-01]]

  [[2.77555756e-16 1.81210462e-01]
   [6.63711401e-01 1.66533454e-16]]]


 [[[2.35922393e-16 6.63711401e-01]
   [1.81210462e-01 1.11022302e-16]]

  [[1.81210462e-01 1.38777878e-16]
   [1.38777878e-16 6.97651504e-01]]]]


In [19]:
second_q_op = hamiltonian.second_q_op()
print(second_q_op)

Fermionic Operator
number spin orbitals=2, number terms=6
  0.3873029719599489 * ( +_0 +_0 -_0 -_0 )
+ 0.3873029719599489 * ( +_0 +_1 -_1 -_0 )
+ 0.3873029719599489 * ( +_1 +_0 -_0 -_1 )
+ 0.3873029719599489 * ( +_1 +_1 -_1 -_1 )
+ -0.46658184955727533 * ( +_0 -_0 )
+ -0.46658184955727533 * ( +_1 -_1 )


# Openfermion

In [29]:
from openfermion.chem import MolecularData 

In [29]:
geometry = [['H', [0, 0, 0]],
            ['H', [0, 0, 0.745]],
            ['H', [0, 0, 1.49]]];

basis = 'sto-3g';
multiplicity = 1;
charge = 0;
h2_molecule = MolecularData(geometry, basis, multiplicity, charge)

In [3]:
from openfermionpyscf import run_pyscf 

In [5]:
h2_molecule = run_pyscf(h2_molecule,
                        run_mp2=True,
                        run_cisd=True,
                        run_ccsd=True,
                        run_fci=True)
h2_filename = h2_molecule.filename
h2_molecule.save()

In [7]:
two_h2 = h2_molecule.two_body_integrals

In [9]:
two_h2.shape

(2, 2, 2, 2)

In [10]:
two_h2

array([[[[ 6.73801841e-01, -2.28983499e-16],
         [-2.22044605e-16,  1.81490576e-01]],

        [[-2.22044605e-16,  1.81490576e-01],
         [ 6.62843238e-01,  2.49800181e-16]]],


       [[[-2.28983499e-16,  6.62843238e-01],
         [ 1.81490576e-01, -1.11022302e-16]],

        [[ 1.81490576e-01, -1.11022302e-16],
         [ 2.49800181e-16,  6.96731985e-01]]]])

# openfermion    NEW

In [1]:
import numpy as np 
import openfermion as of 
import openfermionpyscf as ofps
from scipy.sparse import linalg
# from openfermion.linalg import get_ground_state, get_sparse_operator

In [3]:
for j in range(10):
    print("j= ",j,"\t",j*0.73)

j=  0 	 0.0
j=  1 	 0.73
j=  2 	 1.46
j=  3 	 2.19
j=  4 	 2.92
j=  5 	 3.65
j=  6 	 4.38
j=  7 	 5.109999999999999
j=  8 	 5.84
j=  9 	 6.57


In [2]:
# Set molecule parameters
geometry1 = [("H", (0.0, 0.0, 0.0))];

geometry2 = [("H", (0.0, 0.0, 0.0)),
            ("H", (0.0, 0.0, 0.73))];

geometry3 = [("H", (0.0, 0.0, 0.0)),
            ("H", (0.0, 0.0, 0.73)),
            ("H", (0.0, 0.0, 1.46))];

geometry4 = [("H", (0.0, 0.0, 0.0)),
            ("H", (0.0, 0.0,  0.73)),
            ("H", (0.0, 0.0,  1.46)),
             ("H", (0.0, 0.0, 2.19))];


geometry5 = [("H", (0.0, 0.0, 0.0)),
            ("H", (0.0, 0.0,  0.73)),
            ("H", (0.0, 0.0,  1.46)),
            ("H", (0.0, 0.0, 2.19)),
            ("H", (0.0, 0.0, 2.92))];

geometry6 = [("H", (0.0, 0.0, 0.0)),
            ("H", (0.0, 0.0,  0.73)),
            ("H", (0.0, 0.0,  1.46)),
            ("H", (0.0, 0.0, 2.19)),
            ("H", (0.0, 0.0, 2.92)),
            ("H", (0.0, 0.0, 3.65))];


geometry7 = [("H", (0.0, 0.0, 0.0)),
            ("H", (0.0, 0.0,  0.73)),
            ("H", (0.0, 0.0,  1.46)),
            ("H", (0.0, 0.0, 2.19)),
            ("H", (0.0, 0.0, 2.92)),
            ("H", (0.0, 0.0, 3.65)),
            ("H", (0.0, 0.0, 4.38))];


geometry8 = [("H", (0.0, 0.0, 0.0)),
            ("H", (0.0, 0.0,  0.73)),
            ("H", (0.0, 0.0,  1.46)),
            ("H", (0.0, 0.0, 2.19)),
            ("H", (0.0, 0.0, 2.92)),
            ("H", (0.0, 0.0, 3.65)),
            ("H", (0.0, 0.0, 4.38)),
            ("H", (0.0, 0.0, 5.10))];





basis = "sto-3g";
multiplicity1 = 2;
multiplicity2 = 1;
multiplicity3 = 2;
multiplicity4 = 1;
multiplicity5 = 2;
multiplicity6 = 1;
multiplicity7 = 2;
multiplicity8 = 1;

charge = 0;

# Perform electronic structure calculations and
# obtain Hamiltonian as an InteractionOperator

hamiltonian1 = ofps.generate_molecular_hamiltonian(geometry1, basis, multiplicity1, charge)
hamiltonian2 = ofps.generate_molecular_hamiltonian(geometry2, basis, multiplicity2, charge)
hamiltonian3 = ofps.generate_molecular_hamiltonian(geometry3, basis, multiplicity3, charge)
hamiltonian4 = ofps.generate_molecular_hamiltonian(geometry4, basis, multiplicity4, charge)
hamiltonian5 = ofps.generate_molecular_hamiltonian(geometry5, basis, multiplicity5, charge)
hamiltonian6 = ofps.generate_molecular_hamiltonian(geometry6, basis, multiplicity6, charge)
hamiltonian7 = ofps.generate_molecular_hamiltonian(geometry7, basis, multiplicity7, charge)
hamiltonian8 = ofps.generate_molecular_hamiltonian(geometry8, basis, multiplicity8, charge)



In [3]:
hamiltonian_ferm_op1 = of.get_fermion_operator(hamiltonian1)
hamiltonian_ferm_op2 = of.get_fermion_operator(hamiltonian2)
hamiltonian_ferm_op3 = of.get_fermion_operator(hamiltonian3)
hamiltonian_ferm_op4 = of.get_fermion_operator(hamiltonian4)
hamiltonian_ferm_op5 = of.get_fermion_operator(hamiltonian5)
hamiltonian_ferm_op6 = of.get_fermion_operator(hamiltonian6)
hamiltonian_ferm_op7 = of.get_fermion_operator(hamiltonian7)
hamiltonian_ferm_op8 = of.get_fermion_operator(hamiltonian8)

In [4]:
# Map to QubitOperator using the JWT
hamiltonian_jw1 = of.jordan_wigner(hamiltonian_ferm_op1)
hamiltonian_jw2 = of.jordan_wigner(hamiltonian_ferm_op2)
hamiltonian_jw3 = of.jordan_wigner(hamiltonian_ferm_op3)
hamiltonian_jw4 = of.jordan_wigner(hamiltonian_ferm_op4)
hamiltonian_jw5 = of.jordan_wigner(hamiltonian_ferm_op5)
hamiltonian_jw6 = of.jordan_wigner(hamiltonian_ferm_op6)
hamiltonian_jw7 = of.jordan_wigner(hamiltonian_ferm_op7)
hamiltonian_jw8 = of.jordan_wigner(hamiltonian_ferm_op8)

In [5]:
# Convert to Scipy sparse matrix
hamiltonian_jw_sparse1 = of.get_sparse_operator(hamiltonian_jw1)
hamiltonian_jw_sparse2 = of.get_sparse_operator(hamiltonian_jw2)
hamiltonian_jw_sparse3 = of.get_sparse_operator(hamiltonian_jw3)
hamiltonian_jw_sparse4 = of.get_sparse_operator(hamiltonian_jw4)

In [6]:
hamiltonian_jw_sparse5 = of.get_sparse_operator(hamiltonian_jw5)
hamiltonian_jw_sparse6 = of.get_sparse_operator(hamiltonian_jw6)

In [ ]:
hamiltonian_jw_sparse8 = of.get_sparse_operator(hamiltonian_jw8)

In [7]:
hamiltonian_jw_sparse7 = of.get_sparse_operator(hamiltonian_jw7)

In [ ]:
# Convert to Scipy sparse matrix
hamiltonian_jw_sparse1 = of.get_sparse_operator(hamiltonian_jw1)
hamiltonian_jw_sparse2 = of.get_sparse_operator(hamiltonian_jw2)
hamiltonian_jw_sparse3 = of.get_sparse_operator(hamiltonian_jw3)
hamiltonian_jw_sparse4 = of.get_sparse_operator(hamiltonian_jw4)
hamiltonian_jw_sparse5 = of.get_sparse_operator(hamiltonian_jw5)
hamiltonian_jw_sparse6 = of.get_sparse_operator(hamiltonian_jw6)
hamiltonian_jw_sparse7 = of.get_sparse_operator(hamiltonian_jw7)
hamiltonian_jw_sparse8 = of.get_sparse_operator(hamiltonian_jw8)

In [ ]:
Up to here 

In [9]:
# Compute ground energy
eigvals1, eigvecs1 = linalg.eigsh(hamiltonian_jw_sparse1, k=1, which='SA')
eigvals2, eigvecs2 = linalg.eigsh(hamiltonian_jw_sparse2, k=1, which='SA')
eigvals3, eigvecs3 = linalg.eigsh(hamiltonian_jw_sparse3, k=1, which='SA')
eigvals4, eigvecs4 = linalg.eigsh(hamiltonian_jw_sparse4, k=1, which='SA')
eigvals5, eigvecs5 = linalg.eigsh(hamiltonian_jw_sparse5, k=1, which='SA')
eigvals6, eigvecs6 = linalg.eigsh(hamiltonian_jw_sparse6, k=1, which='SA')
eigvals7, eigvecs7 = linalg.eigsh(hamiltonian_jw_sparse7, k=1, which='SA')
print(eigvals1)
print(eigvals2)
print(eigvals3)
print(eigvals4)
print(eigvals5)
print(eigvals6)
print(eigvals7)

[-0.46658185]
[-1.13728568]
[-1.5203783]
[-2.13200947]
[-2.54400018]
[-3.12823887]
[-3.55858444]


In [10]:
print(eigvecs1.shape, eigvecs2.shape, eigvecs3.shape, 
      eigvecs4.shape, eigvecs5.shape, eigvecs6.shape,
     eigvecs7.shape)

(4, 1) (16, 1) (64, 1) (256, 1) (1024, 1) (4096, 1) (16384, 1)


In [14]:
np.tensordot(np.kron(eigvecs2,eigvecs2),eigvecs4)

array(-0.114603+0.00162226j)

In [18]:
np.linalg.norm(np.tensordot(np.kron(eigvecs2,eigvecs2),eigvecs4))

0.11461448260098572

In [19]:
# overlap H  vs H-H 
print(eigvecs1.shape, eigvecs2.shape)
print(np.linalg.norm(np.tensordot(np.kron(eigvecs1,eigvecs1),eigvecs2)))


(4, 1) (16, 1)
8.108391908423875e-17


In [20]:
# overlap H  vs H-H-H
print(eigvecs1.shape, eigvecs2.shape ,eigvecs3.shape)
print(np.linalg.norm(np.tensordot(np.kron(eigvecs1,np.kron(eigvecs1,eigvecs1)),eigvecs3)))


print("\n")
# overlap H  vs H-H 
print(eigvecs1.shape, eigvecs2.shape, eigvecs3.shape)
print(np.linalg.norm(np.tensordot(np.kron(eigvecs2,eigvecs1),eigvecs3)))

(4, 1) (16, 1) (64, 1)
1.703163940883014e-17


(4, 1) (16, 1) (64, 1)
4.70614409755432e-16


In [21]:
# overlap H  vs H-H-H-H
print(eigvecs1.shape, eigvecs2.shape ,eigvecs3.shape, eigvecs4.shape)
print(np.linalg.norm(np.tensordot(np.kron(eigvecs1,
                                          np.kron(eigvecs1,
                                          np.kron(eigvecs1,eigvecs1))),eigvecs4)))
print("\n")

print(np.linalg.norm(np.tensordot(np.kron(eigvecs1,eigvecs3),eigvecs4)))

print("\n")

print(np.linalg.norm(np.tensordot(np.kron(eigvecs2,eigvecs2),eigvecs4)))

(4, 1) (16, 1) (64, 1) (256, 1)
3.290458810983451e-17


0.007363463080197376


0.11461448260098583


In [22]:
# even hydrogen overlap 
# H-H  vs  H-H-H-H 
print(eigvecs2.shape, eigvecs4.shape, eigvecs6.shape)
print(np.linalg.norm(np.tensordot(np.kron(eigvecs2, eigvecs2) , eigvecs4)))
print("\n")
print(np.linalg.norm(np.tensordot( np.kron(eigvecs4, eigvecs2), eigvecs6)))

(16, 1) (256, 1) (4096, 1)
0.11461448260098583


0.026261070820830595
